# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mechastriessand/eclipse_workspace/RawNTFSExtraction

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mechastriessand/eclipse_workspace/RawNTFSExtraction

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(CMAKE_COMMAND) -E cmake_progress_start /home/mechastriessand/eclipse_workspace/RawNTFSExtraction/CMakeFiles /home/mechastriessand/eclipse_workspace/RawNTFSExtraction/src/CMakeFiles/progress.marks
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mechastriessand/eclipse_workspace/RawNTFSExtraction/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/RawNTFSExtraction.dir/rule:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f CMakeFiles/Makefile2 src/CMakeFiles/RawNTFSExtraction.dir/rule
.PHONY : src/CMakeFiles/RawNTFSExtraction.dir/rule

# Convenience name for target.
RawNTFSExtraction: src/CMakeFiles/RawNTFSExtraction.dir/rule
.PHONY : RawNTFSExtraction

# fast build rule for target.
RawNTFSExtraction/fast:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f src/CMakeFiles/RawNTFSExtraction.dir/build.make src/CMakeFiles/RawNTFSExtraction.dir/build
.PHONY : RawNTFSExtraction/fast

RawNTFSExtraction.o: RawNTFSExtraction.c.o
.PHONY : RawNTFSExtraction.o

# target to build an object file
RawNTFSExtraction.c.o:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f src/CMakeFiles/RawNTFSExtraction.dir/build.make src/CMakeFiles/RawNTFSExtraction.dir/RawNTFSExtraction.c.o
.PHONY : RawNTFSExtraction.c.o

RawNTFSExtraction.i: RawNTFSExtraction.c.i
.PHONY : RawNTFSExtraction.i

# target to preprocess a source file
RawNTFSExtraction.c.i:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f src/CMakeFiles/RawNTFSExtraction.dir/build.make src/CMakeFiles/RawNTFSExtraction.dir/RawNTFSExtraction.c.i
.PHONY : RawNTFSExtraction.c.i

RawNTFSExtraction.s: RawNTFSExtraction.c.s
.PHONY : RawNTFSExtraction.s

# target to generate assembly for a file
RawNTFSExtraction.c.s:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(MAKE) -f src/CMakeFiles/RawNTFSExtraction.dir/build.make src/CMakeFiles/RawNTFSExtraction.dir/RawNTFSExtraction.c.s
.PHONY : RawNTFSExtraction.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RawNTFSExtraction"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... RawNTFSExtraction.o"
	@echo "... RawNTFSExtraction.i"
	@echo "... RawNTFSExtraction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/mechastriessand/eclipse_workspace/RawNTFSExtraction && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

